### ISSUE TITLE
"MouseDriver" class might cause the touchpad driver of a laptop to freeze or crash

### ISSUE THREAD

**Issue by ThirdRealityStudios** [SucukiFarmer/EasyDraw#1]
Generally,
big parts of the program were rewritten which means the bug probably disappeared but there is no guarantee at all.

**Comment by SucukiFarmer** [comment]
I close this issue as it didn't appear anymore for weeks..
I don't know the reason but in the last weeks I actually completely rewrote essential parts of the API.

**Comment by ThirdRealityStudios** [comment]
I close this issue as it didn't appear anymore for weeks..
I don't know the reason but in the last weeks I actually completely rewrote essential parts of the API.
